services:
  - type: web
    name: personal-finance-agent
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
